Measuring equipment/Controllers/PlaceController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Measuring_equipment.Models;
using Microsoft.AspNetCore.Authorization;
using System;

namespace Measuring_equipment.Controllers
{
    [Authorize(Roles = "Administratorzy")]
    public class PlaceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlaceController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Places.Include(p => p.Department);
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlaceId,PlaceName,PlaceDesc,DepartmentId")] Place place)
        {
            if (ModelState.IsValid)
            {
                _context.Add(place);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Zapisano {place.PlaceName}.";
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", place.DepartmentId).OrderBy(x=>x.Text);
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(place);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places.FindAsync(id);
            if (place == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", place.DepartmentId);
            return View(place);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("PlaceId,PlaceName,PlaceDesc,DepartmentId")] Place place)
        {
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(place);
                    await _context.SaveChangesAsync();
                    TempData["message"] = $"Zapisano {place.PlaceName}.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaceExists(place.PlaceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "DepartmentName", place.DepartmentId);
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(place);
        }

        public async Task<IActionResult> Delete(int? placeId)
        {
            if (placeId == null)
            {
                return NotFound();
            }

            var place = await _context.Places
                .Include(p => p.Department)
                .FirstOrDefaultAsync(m => m.PlaceId == placeId);
            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int placeId)
        {
            try
            {
                var place = await _context.Places.FindAsync(placeId);
                _context.Places.Remove(place);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Usunięto {place.PlaceName}.";
            }
            catch (Exception e)
            {
                TempData["error"] = e.Message;
            }
            return RedirectToAction(nameof(Index));
        }

        private bool PlaceExists(int id)
        {
            return _context.Places.Any(e => e.PlaceId == id);
        }
    }
}

Measuring equipment/Controllers/TypeController.cs
using Microsoft.AspNetCore.Mvc;
using Measuring_equipment.Models;
using System.Linq;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System;
using Type = Measuring_equipment.Models.Type;
using Microsoft.AspNetCore.Authorization;
using LinqKit;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Measuring_equipment.Models.ViewModels;


namespace Measuring_equipment.Controllers
{
    [Authorize(Roles = "Administratorzy")]
    public class TypeController : Controller
    {
        private ITypeRepository repository;
        private readonly UserManager<AppUser> userManager;
        public TypeController(ITypeRepository repo, UserManager<AppUser> userMgr)
        {
            repository = repo;
            userManager = userMgr;
        }

        public IActionResult Index()
        {
            ViewBag.Breadcrumb = "Index";
            return View();
        }


        public async Task<IActionResult> Edit(int? typeId)
        {
            if (typeId == null)
            {
                TempData["error"] = $"Nie odnaleziono.";
                return RedirectToAction("Index");
            }

            Type type = repository.Types.FirstOrDefault(t => t.TypeId == typeId);

            if (type == null)
            {
                TempData["error"] = $"Nie odnaleziono.";
                return RedirectToAction("Index");
            }

            List<SelectListItem> prodList = await ProducerList();
            List<SelectListItem> labList = await LaboratoryList();
            List<SelectListItem> verList = await VerificationList();

            //Type picture
            string imgSrc = Url.Content("~/images/no_pic.jpg");
            if (type.Image != null)
            {
                var base64 = Convert.ToBase64String(type.Image);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }

            TypeEditViewModel model = new TypeEditViewModel
            {
                TypeId = type.TypeId,
                TypeName = type.TypeName,
                DeviceName = type.DeviceName,
                ValidityPierod = type.ValidityPierod,
                Price = type.Price,
                Image = type.Image,
                TypeDesc = type.TypeDesc,
                ProducerId = type.ProducerId,
                LaboratoryId = type.LaboratoryId,
                VerificationId = type.VerificationId,
                ImageStr = imgSrc,
                ProducerListVm = prodList,
                LaboratoryListVm = labList,
                VerificationListVm = verList,
                ReturnUrl = HttpContext.Request.Headers["Referer"]
        };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("TypeId,TypeName,DeviceName,ValidityPierod,Price,Image,TypeDesc,ProducerId,LaboratoryId,VerificationId")] TypeEditViewModel model)
        {
            if (ModelState.IsValid)
                try
                {
                        Type type = new Type
                        {
                            TypeId = model.TypeId,
                            TypeName = model.TypeName,
                            DeviceName = model.DeviceName,
                            ValidityPierod = model.ValidityPierod,
                            Price = model.Price,
                            Image = model.Image,
                            TypeDesc = model.TypeDesc,
                            ProducerId = model.ProducerId,
                            LaboratoryId = model.LaboratoryId,
                            VerificationId = model.VerificationId,
                        };

                        if (HttpContext.Request.Form.Files.Count != 0)
                        {
                            var file = HttpContext.Request.Form.Files[0];
                            using (var stream = new MemoryStream())
                            {
                                await file.CopyToAsync(stream);
                                type.Image = stream.ToArray();
                            }
                        }

                        else
                        {
                            if (type.TypeId != 0)
                            {
                                Type tmp = await repository.Types.FirstAsync(t => t.TypeId == type.TypeId);
                                type.Image = tmp.Image;
                            }
                        }

                        repository.SaveType(type);
                        TempData["message"] = $"Zapisano {type.TypeName}.";
                        return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("Nie można zapisać zmian", e.Message);
                    return await Edit(model.TypeId);
                }
            else
            {
                TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";

                List<SelectListItem> prodList = await ProducerList();
                List<SelectListItem> labList = await LaboratoryList();
                List<SelectListItem> verList = await VerificationList();

                return await Edit(model.TypeId);
            }
        }

        public async Task<ViewResult> Create()
        {
            //  Producers, Labs and Veryfications values for select options
            List<SelectListItem> prodList = await ProducerList();
            List<SelectListItem> labList = await LaboratoryList();
            List<SelectListItem> verList = await VerificationList();

            return View("Create", new TypeEditViewModel {
                ProducerListVm = prodList,
                LaboratoryListVm = labList,
                VerificationListVm = verList,
                ReturnUrl = HttpContext.Request.Headers["Referer"]
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("TypeId,TypeName,DeviceName,ValidityPierod,Price,Image,TypeDesc,ProducerId,LaboratoryId,VerificationId,ReturnUrl")] TypeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                try {
                    Type type = new Type
                    {
                        TypeId = model.TypeId,
                        TypeName = model.TypeName,
                        DeviceName = model.DeviceName,
                        ValidityPierod = model.ValidityPierod,
                        Price = model.Price,
                        Image = model.Image,
                        TypeDesc = model.TypeDesc,
                        ProducerId = model.ProducerId,
                        LaboratoryId = model.LaboratoryId,
                        VerificationId = model.VerificationId,
                    };

                    if (HttpContext.Request.Form.Files.Count != 0)
                    {
                        var file = HttpContext.Request.Form.Files[0];
                        using (var stream = new MemoryStream())
                        {
                            await file.CopyToAsync(stream);
                            type.Image = stream.ToArray();
                        }
                    }
                    else
                    {
                        if (type.TypeId != 0)
                        {
                            Type tmp = await repository.Types.FirstAsync(t => t.TypeId == type.TypeId);
                            type.Image = tmp.Image;
                        }
                    }

                    repository.SaveType(type);
                    TempData["message"] = $"Zapisano {type.TypeName}.";
                    return Redirect(model.ReturnUrl);

                }
                catch (Exception e)
                {
                    ModelState.AddModelError("Nie można utworzyć typu", e.Message);
                    return await Create();
                }
            }
            else
            {
                TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
                return await Create();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int typeId)
        {
            try
            {
                Type deletedType = await repository.DeleteTypeAsync(typeId);
                if (deletedType != null)
                {
                    TempData["message"] = $"Usunięto {deletedType.TypeName}.";
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Nie można usunąć, istnieją urządzenia tego typu", e.Message);
                TempData["error"] = $"Nie można usunąć, istnieją urządzenia tego typu";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> LoadData()
        {
            // DataTable Server side processing

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

            // Skip number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();

            // Paging Length   
            var length = Request.Form["length"].FirstOrDefault();

            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

            // Sort Column Direction (asc, desc)  
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

            // Search Value from (Search box)  
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            //Paging Size  
            int pageSize = length != null ? Convert.ToInt32(length) : 0;

Measuring equipment/Views/Admin/Create.cshtml
@model AdminEditViewModel
@{
    ViewData["Title"] = "Dodawanie nowego przyrządu";
    
    Layout = "_AdminLayout";
}

<form asp-action="Create" method="post">
    <input type="hidden" asp-for="DeviceId" />
    <div class=" row">
        <div class="border col-md-12">
            <div class="form-group ">
                <label asp-for="RegistrationNo">Numer kalibracji</label>
                <input asp-for="RegistrationNo" value="@String.Format("{0:D5}",Model.RegistrationNo)" class="form-control" readonly />
                <div><span asp-validation-for="RegistrationNo" class="text-danger"></span></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6  border">
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="DeviceName">Nazwa przyrządu</label>
                    <input asp-for="DeviceName" class="form-control" readonly />
                    <div><span asp-validation-for="DeviceName" class="text-danger"></span></div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="ProducerName">Producent</label>
                    <input asp-for="ProducerName" class="form-control" readonly />
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="TypeId">Typ urządzenia</label>
                    <div class="btn-group btn-block">
                        <select class="form-control" asp-for="TypeId" asp-items="Model.TypeListVm">
                            <option disabled selected value="">Wybierz typ</option>
                        </select>
                        <a asp-controller="Type" asp-action="Create" class="btn btn-secondary">Dodaj</a>
                    </div>
                    <div><span asp-validation-for="TypeId" class="text-danger"></span></div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="SerialNo">Numer seryjny</label>
                    <input asp-for="SerialNo" class="form-control" />
                    <div><span asp-validation-for="SerialNo" class="text-danger"></span></div>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ProductionDate">Data produkcji</label>
                    <div><span asp-validation-for="ProductionDate" class="text-danger"></span></div>
                    <div class="input-group date dtp" id="dtp1" data-target-input="nearest">
                        <input asp-for="ProductionDate" type="text" class="form-control datetimepicker-input" data-target="#dtp1" />
                        <div class="input-group-append" data-target="#dtp1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="CurrentlyInUse">W użytkowaniu</label>
                    <input asp-for="CurrentlyInUse" class="form-control" />
                    <div><span asp-validation-for="CurrentlyInUse" class="text-danger"></span></div>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="InventoryNo">Numer inwentarzowy</label>
                    <input asp-for="InventoryNo" class="form-control" />
                    <div><span asp-validation-for="InventoryNo" class="text-danger"></span></div>
                </div>
            </div>
        </div>
        <div class="col-md-6 border">
            <div class="img-max mx-auto p-2">
                <img id="Image" class="img-fluid mx-auto d-block" src="@Model.ImageStr" alt="">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 border">
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="VerificationName">Rodzaj weryfikacji</label>
                    <input asp-for="VerificationName" class="form-control" readonly />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="VerificationDate">Data weryfikacji</label>
                    <div><span asp-validation-for="VerificationDate" class="text-danger"></span></div>
                    <div class="input-group date dtp ver" id="dtp3" data-target-input="nearest">
                        <input asp-for="VerificationDate" type="text" class="form-control datetimepicker-input" data-target="#dtp3" />
                        <div id="dupa" class="input-group-append" data-target="#dtp3" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="TimeToVerification">Czas kolejnej weryfikacji</label>
                    <div><span asp-validation-for="TimeToVerification" class="text-danger"></span></div>
                    <div class="input-group date dtp" id="dtp2" data-target-input="nearest">
                        <input asp-for="TimeToVerification" type="text" class="form-control datetimepicker-input" data-target="#dtp2" readonly />
                        <div class="input-group-append" data-target="#dtp2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="EngName">Osoba wprowadzająca</label>
                    <input id="EngName" class="form-control" value="@User.Identity.Name" readonly />
                </div>
                <div class="form-group col-md-6">
                    <label for="Future">Future field</label>
                    <input id="Future" class="form-control" readonly />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label asp-for="VerificationResult">Wynik weryfikacji</label>
                    <input asp-for="VerificationResult" class="form-control" />
                    <div><span asp-validation-for="VerificationResult" class="text-danger"></span></div>
                </div>
            </div>
        </div>
        <div class="border col-md-6">
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="PlaceId">Miejsce użytkowania</label>
                    <div class="btn-group btn-block">
                        <select class="form-control" asp-for="PlaceId" asp-items="Model.PlaceListVm">
                            <option disabled selected value="">Wybierz miejsce</option>
                        </select>
                        <a asp-controller="Place" asp-action="Create" class="btn btn-secondary">Dodaj</a>
                    </div>
                    <div><span asp-validation-for="PlaceId" class="text-danger"></span></div>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="DepartmentName">Dział</label>
                    <input asp-for="DepartmentName" class="form-control" readonly />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="UserId">Osoba odpowiedzialna</label>
                    <div class="btn-group btn-block">
                        <select class="form-control" asp-for="UserId" asp-items="Model.UserListVm">
                            <option disabled selected value="">Wybierz osobę</option>
                        </select>
                        <a asp-controller="Admin" asp-action="UsersCreate" class="btn btn-secondary">Dodaj</a>
                    </div>
                    <div><span asp-validation-for="UserId" class="text-danger"></span></div>
                </div>
                <div class="form-group col-md-6">
                    <label for="Future">Future field</label>
                    <input id="Future" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label asp-for="ValidityPierod">Czasokres weryfikacji</label>
                    <input asp-for="ValidityPierod" class="form-control" readonly />
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="LaboratoryName">Laboratorium</label>
                    <input asp-for="LaboratoryName" class="form-control" readonly />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label for="Print">Drukowanie</label><br />
                    <a id="Print" class="btn btn-block btn-secondary">Drukuj Etykietę</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="border col-md-12">
            <div class="form-group">
                <label asp-for="DeviceDesc">Uwagi</label>
                <div><span asp-validation-for="DeviceDesc" class="text-danger"></span></div>
                <textarea asp-for="DeviceDesc" class="form-control" rows="3"></textarea>
            </div>
        </div>
    </div>
    <br />
    <span style="float:left;">
        <button class="btn btn-primary" type="submit">Zapisz</button>
        <a asp-controller="Admin" asp-action="Index" class="btn btn-secondary">Anuluj</a>
    </span>
</form>

Measuring equipment/Views/Admin/Index.cshtml
@model IEnumerable<Device>
@{
    ViewBag.Title = "Lista sprzętu pomiarowego";
    Layout = "_AdminLayout";

}

        <table id="dt_device" class="table table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th>Id urządzenia</th>
                    <th>Nr kalibracji</th>
                    <th>Nr inwentarzowy</th>
                    <th>Nr seryjny</th>
                    <th>Data weryfikacji</th>
                    <th>Data następnej</th>
                    <th>Wynik weryfikacji</th>
                    <th>Data produkcji</th>
                    <th>Opis</th>
                    <th>Nazwa urządzenia</th>
                    <th>Typ</th>
                    <th>Edycja</th>
                </tr>
            </thead>
        </table>
    
    <br />
    <div class="text-left">
        <a asp-action="Create" class="btn btn-primary">Dodaj urządzenie</a>
    </div>

Measuring equipment/Views/Admin/List.cshtml
@model IEnumerable<Device>
@{
    ViewBag.Title = "Lista sprzętu do weryfikacji do dnia " + DateTime.Today.AddMonths(1).ToShortDateString();
    Layout = "_AdminLayout";

}

    <table id="dt_list" class="table table-bordered table-hover" width="100%">
        <thead>
            <tr>
                <th>Numer kalibracji</th>
                <th>Nazwa urządzenia</th>
                <th>Producent</th>
                <th>Typ urządzenia</th>
                <th>Numer seryjny</th>
                <th data-priority="1">Miejsce użytkowania</th>
                <th>Odpowiedzialny</th>
                <th>Data Nast. Wer.</th>

                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var d in Model)
            {
                <tr>
                    <td>@String.Format("{0:D5}", d.RegistrationNo) </td>
                    <td>@d.Type.DeviceName</td>
                    <td>@d.Type.Producer.ProducerName</td>
                    <td>@d.Type.TypeName</td>
                    <td>@d.SerialNo</td>
                    <td>@d.Place.PlaceName</td>
                    <td>@d.UserId</td>
                    <td>@d.TimeToVerification.Value.ToShortDateString()</td>

                    <td>
                        <a asp-action="Edit" class="btn btn-sm btn-info" asp-route-deviceId="@d.DeviceId">Edytuj</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

Measuring equipment/Views/Admin/PrintLabel.cshtml
@model AdminEditViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PrintLabel</title>
    <link asp-href-include="lib\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet">
</head>
<body>
    @if (TempData["error"] != null)
    {
        <div class="alert alert-danger mt-1">@TempData["error"]</div>
    }
    <form asp-action="PrintLabel" method="post">
        <input type="hidden" asp-for="DeviceId" />
        <div id="printlabel">
            <div class="row">
                <div class="border col-2">
                    <div class="img-max mx-auto p-1">
                        <img class="img-fluid mx-auto d-block" src="@Url.Content("~/images/logo.png")" alt="">
                        <div class=" text-center ">Laboratorim kalibracji</div>
                    </div>
                </div>
                <div class="border col-6">
                    <div class="form-group text-center">
                        <label asp-for="RegistrationNo">Numer idnetyfikacyjny</label>
                        <h3 class="text-center">@String.Format("{0:D5}", Model.RegistrationNo)</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="border col-4">
                    <div class="form-group text-center">
                        <label asp-for="VerificationDate">Data weryfikacji</label>
                        <h3 class="text-center">@Model.VerificationDate.Value.ToShortDateString()</h3>
                    </div>
                </div>
                <div class="border col-4 text-center">
                    <div class="form-group ">
                        <label asp-for="TimeToVerification">Data następnej wer.</label>
                        <h3 class="text-center">@Model.TimeToVerification.Value.ToShortDateString()</h3>
                    </div>
                </div>
            </div>
            <div class="row ">
                <div class="col-8">
                    <p class="text-center small">@Model.VerificationResult</p>
                </div>
            </div>
        </div>
    </form>
    <br />
    <div class="btn-block ">
        <button id="print" class="btn btn-primary print">Drukuj</button>
        <a class="btn btn-danger" href="javascript:window.close()">Zamknij</a>
    </div>

    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/printThis/1.14.0/printThis.min.js"></script>

    <script>
        $(function () {
            $("#print").click(function () {
                $("#printlabel").printThis({
                    importCSS: true,
                    header: null,
                    printContainer: true
                });
            });
        });
    </script>
</body>
</html>

Measuring equipment/Views/Admin/UsersCreate.cshtml
@model UserViewModel.CreateModel
@{
    Layout = "_AdminLayout";
}

<form asp-action="UsersCreate" method="post">
    <input type="hidden" asp-for="ReturnUrl" value="@Model.ReturnUrl" />
    <div class="form-group">
        <label asp-for="Name">Nazwa użytkownika</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Email">Adres e-mail</label>
        <input asp-for="Email" class=" form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password">Hasło</label>
        <input asp-for="Password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Utwórz</button>
    <a href="@Model.ReturnUrl" class="btn btn-secondary">Anuluj</a>
</form>