Measuring equipment/Models/Verification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Measuring_equipment.Models
{
    public class Verification
    {
        public int VerificationId { get; set; }
        public string VerificationName { get; set; }
        public string VerificationDesc { get; set; }
        public virtual ICollection<Type> Types { get; set; }
    }
}

Measuring equipment/Controllers/VerificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Measuring_equipment.Models;

namespace Measuring_equipment.Controllers
{
    public class VerificationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VerificationController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index() => View(await _context.Verification.ToListAsync());

        public IActionResult Create() => View();
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VerificationId,VerificationName,VerificationDesc")] Verification verification)
        {
            if (ModelState.IsValid)
            {
                _context.Add(verification);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Zapisano {verification.VerificationName}.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(verification);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var verification = await _context.Verification.FindAsync(id);
            if (verification == null)
            {
                return NotFound();
            }
            return View(verification);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VerificationId,VerificationName,VerificationDesc")] Verification verification)
        {
           if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(verification);
                    await _context.SaveChangesAsync();
                    TempData["message"] = $"Zapisano {verification.VerificationName}.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VerificationExists(verification.VerificationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(verification);
        }

        public async Task<IActionResult> Delete(int? verificationId)
        {
            if (verificationId == null)
            {
                return NotFound();
            }

            var verification = await _context.Verification
                .FirstOrDefaultAsync(m => m.VerificationId == verificationId);
            if (verification == null)
            {
                return NotFound();
            }

            return View(verification);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int verificationId)
        {
            var verification = await _context.Verification.FindAsync(verificationId);
            _context.Verification.Remove(verification);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VerificationExists(int id)
        {
            return _context.Verification.Any(e => e.VerificationId == id);
        }
    }
}

Measuring equipment/Views/Verification/Create.cshtml
@model Measuring_equipment.Models.Verification

@{
    ViewData["Title"] = "Dodawanie rodzaju weryfikacji";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="VerificationName" class="control-label">Nazwa</label>
                <input asp-for="VerificationName" class="form-control" />
                <span asp-validation-for="VerificationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerificationDesc" class="control-label">Opis</label>
                <input asp-for="VerificationDesc" class="form-control" />
                <span asp-validation-for="VerificationDesc" class="text-danger"></span>
            </div>
            <br />
            <span style="float:left;">
                <button class="btn btn-primary" type="submit">Zapisz</button>
                <a asp-action="Index" class="btn btn-secondary">Anuluj</a>
            </span>
        </form>
    </div>
</div>

Measuring equipment/Views/Verification/Delete.cshtml
@model Measuring_equipment.Models.Verification

@{
    ViewData["Title"] = "Usuwanie weryfikacji";
    Layout = "_AdminLayout";
}

<h3>Na pewno chcesz usunąć tą pozycję?</h3>
<br />
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nazwa
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerificationName)
        </dd>
        <dt>
            Opis
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerificationDesc)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="VerificationId" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-primary">Anuluj</a>
    </form>
</div>

Measuring equipment/Views/Verification/Details.cshtml
@model Measuring_equipment.Models.Verification

@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}

<h2>Details</h2>

<div>
    <h4>Verification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VerificationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerificationName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerificationDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerificationDesc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VerificationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Measuring equipment/Views/Verification/Edit.cshtml
@model Measuring_equipment.Models.Verification

@{
    ViewData["Title"] = "Edycja rodzaju weryfikacji";
    Layout = "_AdminLayout";
}

<form asp-action="Edit" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="VerificationId" />
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="VerificationName" class="control-label">Nazwa</label>
                <input asp-for="VerificationName" class="form-control" />
                <span asp-validation-for="VerificationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerificationDesc" class="control-label">Opis</label>
                <input asp-for="VerificationDesc" class="form-control" />
                <span asp-validation-for="VerificationDesc" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <span style="float:left;">
        <button class="btn btn-primary" type="submit">Zapisz</button>
        <a class="btn btn-secondary" asp-controller="Verification" asp-action="Index">Anuluj</a>
    </span>
</form>

<form asp-action="Delete" method="get" asp-route-id="@Model.VerificationId">
    <span style="float:left; margin-left:4px">
        <input type="hidden" asp-for="VerificationId" />
        <button type="submit" class="btn btn-danger">Usuń</button>

    </span>
</form>

Measuring equipment/Views/Verification/Index.cshtml
@model IEnumerable<Measuring_equipment.Models.Verification>

@{
    ViewData["Title"] = "Rodzaje weryfikacji";
    Layout = "_AdminLayout";
}

<table class="table table-bordered table-hover" id="dt_rest" width="100%">
    <thead>
        <tr>
            <th>
               Nazwa
            </th>
            <th>
                Opis
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VerificationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VerificationDesc)
                </td>
                <td>
                    <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@item.VerificationId">Edycja</a> 
            </tr>
        }
    </tbody>
</table>
<br />
<p>
    <a class="btn btn-primary" asp-action="Create">Dodaj nowy</a>
</p>