Measuring equipment/Models/Producer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Measuring_equipment.Models
{
    public class Producer
    {
        public int ProducerId { get; set; }
        public string ProducerName { get; set; }
        public string ProducerDesc { get; set; }
        public virtual ICollection<Type> Types { get; set; }
    }
}

Measuring equipment/Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Measuring_equipment.Models;

namespace Measuring_equipment.Controllers
{
    public class ProducerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProducerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index() => View(await _context.Producers.ToListAsync());
        

        public IActionResult Create() => View();
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProducerId,ProducerName,ProducerDesc")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producer);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Zapisano {producer.ProducerName}.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(producer);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producer = await _context.Producers.FindAsync(id);
            if (producer == null)
            {
                return NotFound();
            }
            return View(producer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProducerId,ProducerName,ProducerDesc")] Producer producer)
        {
            if (id != producer.ProducerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producer);
                    await _context.SaveChangesAsync();
                    TempData["message"] = $"Zapisano {producer.ProducerName}.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProducerExists(producer.ProducerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = $"Uzupełnij poprawnie wszystkie wymagane dane";
            return View(producer);
        }

        public async Task<IActionResult> Delete(int? producerId)
        {
            if (producerId == null)
            {
                return NotFound();
            }

            var producer = await _context.Producers
                .FirstOrDefaultAsync(m => m.ProducerId == producerId);
            if (producer == null)
            {
                return NotFound();
            }

            return View(producer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int producerId)
        {
            try
            {
                var producer = await _context.Producers.FindAsync(producerId);
                _context.Producers.Remove(producer);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Usunięto {producer.ProducerName}.";
            }
            catch
            {
                TempData["error"] = $"Nie można usunąć, istnieją typy powiązane z tym producentem";
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ProducerExists(int id)
        {
            return _context.Producers.Any(e => e.ProducerId == id);
        }
    }
}

Measuring equipment/Views/Producer/Create.cshtml
@model Measuring_equipment.Models.Producer

@{
    ViewData["Title"] = "Dodawanie producenta";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProducerName" class="control-label">Nazwa</label>
                <input asp-for="ProducerName" class="form-control" />
                <span asp-validation-for="ProducerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProducerDesc" class="control-label">Opis</label>
                <input asp-for="ProducerDesc" class="form-control" />
                <span asp-validation-for="ProducerDesc" class="text-danger"></span>
            </div>
            <span style="float:left;">
                <button class="btn btn-primary" type="submit">Zapisz</button>
                <a asp-action="Index" class="btn btn-secondary">Anuluj</a>
            </span>
        </form>
    </div>
</div>

Measuring equipment/Views/Producer/Delete.cshtml
@model Measuring_equipment.Models.Producer

@{
    ViewData["Title"] = "Usuwanie producenta";
    Layout = "_AdminLayout";
}

<h3>Na pewno chcesz usunąć tą pozycję?</h3>
<br />
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nazwa
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerName)
        </dd>
        <dt>
            Opis
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerDesc)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ProducerId" />
        <input type="submit" value="Usuń" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Anuluj</a>
    </form>
</div>

Measuring equipment/Views/Producer/Details.cshtml
@model Measuring_equipment.Models.Producer

@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}

<h2>Details</h2>

<div>
    <h4>Producer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProducerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProducerDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProducerDesc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProducerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Measuring equipment/Views/Producer/Edit.cshtml
@model Measuring_equipment.Models.Producer

@{
    ViewData["Title"] = "Edycja producenta";
    Layout = "_AdminLayout";
}


<form asp-action="Edit">
    <div class="row">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProducerId" />
            <div class="form-group">
                <label asp-for="ProducerName" class="control-label">Nazwa</label>
                <input asp-for="ProducerName" class="form-control" />
                <span asp-validation-for="ProducerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProducerDesc" class="control-label">Opis</label>
                <input asp-for="ProducerDesc" class="form-control" />
                <span asp-validation-for="ProducerDesc" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <span style="float:left;">
        <button class="btn btn-primary" type="submit">Zapisz</button>
        <a class="btn btn-secondary" asp-controller="Producer" asp-action="Index">Anuluj</a>
    </span>
</form>

<form asp-action="Delete" method="get" asp-route-placeId="@Model.ProducerId">
    <span style="float:left; margin-left:4px">
        <input type="hidden" asp-for="ProducerId" />
        <button type="submit" class="btn btn-danger">Usuń</button>
    </span>
</form>

Measuring equipment/Views/Producer/Index.cshtml
@model IEnumerable<Measuring_equipment.Models.Producer>

@{
    ViewData["Title"] = "Producenci";
    Layout = "_AdminLayout";
}

<table class="table table-bordered table-hover" id="dt_rest" width="100%">
    <thead>
        <tr>
            <th>Nazwa</th>
            <th>Opis</th>
            <th>Edycja</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProducerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProducerDesc)
            </td>
            <td>
                <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@item.ProducerId">Edycja</a>
        </tr>
}
    </tbody>
</table>
<br />
<p>
    <a class="btn btn-primary" asp-action="Create">Dodaj producenta</a>
</p>