Measuring equipment/Models/Laboratory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Measuring_equipment.Models
{
    public class Laboratory
    {
        public int LaboratoryId { get; set; }
        public string LaboratoryName { get; set; }
        public string Accreditation { get; set; }
        public string LaboratoryDesc { get; set; }
        public virtual ICollection<Type> Types { get; set; }
    }
}

Measuring equipment/Controllers/LaboratoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Measuring_equipment.Models;

namespace Measuring_equipment.Controllers
{
    public class LaboratoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LaboratoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Laboratory
        public async Task<IActionResult> Index()
        {
            return View(await _context.Laboratories.ToListAsync());
        }

        // GET: Laboratory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laboratory = await _context.Laboratories
                .FirstOrDefaultAsync(m => m.LaboratoryId == id);
            if (laboratory == null)
            {
                return NotFound();
            }

            return View(laboratory);
        }

        // GET: Laboratory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Laboratory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LaboratoryId,LaboratoryName,Accreditation,LaboratoryDesc")] Laboratory laboratory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(laboratory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(laboratory);
        }

        // GET: Laboratory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laboratory = await _context.Laboratories.FindAsync(id);
            if (laboratory == null)
            {
                return NotFound();
            }
            return View(laboratory);
        }

        // POST: Laboratory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LaboratoryId,LaboratoryName,Accreditation,LaboratoryDesc")] Laboratory laboratory)
        {
            if (id != laboratory.LaboratoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(laboratory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LaboratoryExists(laboratory.LaboratoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(laboratory);
        }

        // GET: Laboratory/Delete/5
        public async Task<IActionResult> Delete(int? laboratoryId)
        {
            if (laboratoryId == null)
            {
                return NotFound();
            }

            var laboratory = await _context.Laboratories
                .FirstOrDefaultAsync(m => m.LaboratoryId == laboratoryId);
            if (laboratory == null)
            {
                return NotFound();
            }

            return View(laboratory);
        }

        // POST: Laboratory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int laboratoryId)
        {
            var laboratory = await _context.Laboratories.FindAsync(laboratoryId);
            _context.Laboratories.Remove(laboratory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LaboratoryExists(int id)
        {
            return _context.Laboratories.Any(e => e.LaboratoryId == id);
        }
    }
}

Measuring equipment/Views/Laboratory/Create.cshtml
@model Measuring_equipment.Models.Laboratory

@{
    ViewData["Title"] = "Dodawanie laboratoirium";
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LaboratoryName" class="control-label">Nazwa</label>
                <input asp-for="LaboratoryName" class="form-control" />
                <span asp-validation-for="LaboratoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accreditation" class="control-label">Akredytacja</label>
                <input asp-for="Accreditation" class="form-control" />
                <span asp-validation-for="Accreditation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratoryDesc" class="control-label">Opis</label>
                <input asp-for="LaboratoryDesc" class="form-control" />
                <span asp-validation-for="LaboratoryDesc" class="text-danger"></span>
            </div>
            <br />
            <span style="float:left;">
                <button class="btn btn-primary" type="submit">Zapisz</button>
                <a asp-action="Index" class="btn btn-secondary">Anuluj</a>
            </span>
        </form>
    </div>
</div>

Measuring equipment/Views/Laboratory/Delete.cshtml
@model Measuring_equipment.Models.Laboratory

@{
    ViewData["Title"] = "Usuwanie laboratorium";
    Layout = "_AdminLayout";
}

<h3>Na pewno chcesz usunąć tą pozycję?</h3>
<br />
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nazwa
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LaboratoryName)
        </dd>
        <dt>
            Akredytacja
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Accreditation)
        </dd>
        <dt>
            Opis
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LaboratoryDesc)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="LaboratoryId" />
        <input type="submit" value="Usuń" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Anuluj</a>
    </form>
</div>

Measuring equipment/Views/Laboratory/Details.cshtml
@model Measuring_equipment.Models.Laboratory

@{
    ViewData["Title"] = "Details";
    Layout = "_AdminLayout";
}

<h2>Details</h2>

<div>
    <h4>Laboratory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LaboratoryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LaboratoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Accreditation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Accreditation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LaboratoryDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LaboratoryDesc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LaboratoryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Measuring equipment/Views/Laboratory/Edit.cshtml
@model Measuring_equipment.Models.Laboratory

@{
    ViewData["Title"] = "Edycja laboratorium";
    Layout = "_AdminLayout";
}


<form asp-action="Edit">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LaboratoryId" />
            <div class="form-group">
                <label asp-for="LaboratoryName" class="control-label">Nazwa</label>
                <input asp-for="LaboratoryName" class="form-control" />
                <span asp-validation-for="LaboratoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accreditation" class="control-label">Akredytacja</label>
                <input asp-for="Accreditation" class="form-control" />
                <span asp-validation-for="Accreditation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratoryDesc" class="control-label">Opis</label>
                <input asp-for="LaboratoryDesc" class="form-control" />
                <span asp-validation-for="LaboratoryDesc" class="text-danger"></span>
            </div>
        </div>
    </div>
    <br />
    <span style="float:left;">
        <button class="btn btn-primary" type="submit">Zapisz</button>
        <a class="btn btn-secondary" asp-controller="Laboratory" asp-action="Index">Anuluj</a>
    </span>
</form>
<form asp-action="Delete" method="get" asp-route-id="@Model.LaboratoryId">
    <span style="float:left; margin-left:4px">
        <input type="hidden" asp-for="LaboratoryId" />
        <button type="submit" class="btn btn-danger">Usuń</button>
    </span>
</form>

Measuring equipment/Views/Laboratory/Index.cshtml
@model IEnumerable<Measuring_equipment.Models.Laboratory>

@{
    ViewData["Title"] = "Laboratoria";
    Layout = "_AdminLayout";
}


<table class="table table-bordered table-hover" id="dt_rest" width="100%">
    <thead>
        <tr>
            <th>
                Nazwa
            </th>
            <th>
                Akredytacja
            </th>
            <th>
                Opis
            </th>
            <th>Edycja</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LaboratoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Accreditation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LaboratoryDesc)
                </td>
                <td>
                    <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@item.LaboratoryId">Edycja</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<p>
    <a class="btn btn-primary" asp-action="Create">Dodaj laboratorium</a>
</p>